spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/sifap
    username: sifap
    password: sifap_local
  jpa:
    show-sql: false
  flyway:
    enabled: true

logging:
  level:
    com.datacorp.sifap: INFO
